sudo: required
services:
  - docker

before_install:
  - docker build -t test-build -f Dockerfile.dev .

script:
  - docker run test-build npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "websocket"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-123884313216"
  bucket_path: "websocket"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
